apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gloo
  name: gloo
  namespace: project
spec:
  rules:
    - host: casos.covid19so1.tk
      http:
        paths:
          - path: /
            backend:
              serviceName: goservicermq
              servicePort: 80
          - path: /caso
            backend:
              serviceName: goservicermq
              servicePort: 80