apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-webserver-rmq
  name: goservicermq
  namespace: project
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: go-webserver-rmq
