apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-web-app
  name: react-web-app-service
  namespace: frontend
spec:
  ports:
  - nodePort: 31902
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: react-web-app
  type: LoadBalancer