apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-webserver-grpc
  name: go-service-grpc
  namespace: project
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: go-webserver-grpc
