apiVersion: v1
kind: Service
metadata:
  labels:
    app: pyserver-grpc
  name: python-service-grpc
  namespace: project
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: pyserver-grpc
